### PR TITLE
Migration to Scala 2.10

### PR DESCRIPTION
**Pull request by AnishShah**
Unified util-core, util-logging, util-app to 6.23.0
Changed to 2.10.3 in .travis.yml

### CODE REVIEW

**Comment by AnishShah** [comment]
@szymonm @pankajgupta Is this OK? Travis gives some Deprecation Warnings. I'll try to fix it.

**Comment by szymonm** [comment]
Looks good, only the warnings - this shouldn't be hard.

**Comment by AnishShah** [comment]
Travis log still gives on warning. 
```
[warn] warning: [options] bootstrap class path not set in conjunction with -source 1.6
[warn] 1 warning
[warn] there were 1 feature warning(s); re-run with -feature for details
[warn] one warning found
```

**Comment by caniszczyk** [comment]
good enough, can focus on moving to 2.11 now :)

**Pull request merged**
