### PR TITLE
Move to Scala 2.11

### PR DESCRIPTION
**Pull request by caniszczyk**
Signed-off-by: Chris Aniszczyk <zx@twitter.com>

### CODE REVIEW

**Comment by travisbrown** [comment]
Hey @caniszczyk, it'd probably be best to set this up to continue cross-publish 2.10 as well, and we might as well bump to 2.11.5 while we're at it. I can file a PR in a second with the changes.

**Comment by caniszczyk** [comment]
@travisbrown I'm trying to avoid cross publishing in this case, I don't think we need too IMHO, 2.10 is already pretty old :)

**Comment by szymonm** [comment]
@caniszczyk You also need to bump Scalatest to newest version.

**Comment by travisbrown** [comment]
And `finagle-stats`, since we don't have 2.11 builds until 6.24.0.

**Comment by caniszczyk** [comment]
@travisbrown done

**Comment by pankajgupta** [comment]
hey @caniszczyk , I think I agree with @travisbrown that it would be good to continue cross publishing scala 2.10 .

**Comment by pankajgupta** [comment]
We can deprecate scala 2.10 in a few months...

**Comment by pankajgupta** [comment]
@caniszczyk travis ci build is failing for this PR.

**Comment by caniszczyk** [comment]
@pankajgupta yep looks like some changes in the matchers package since scalatest 2.10, looking to fix it

**Comment by caniszczyk** [comment]
The specs are fixed now to run with 2.11, not sure why Travis CI doesn't want to build for me

**Comment by pankajgupta** [comment]
Thanks for fixing! Thoughts on continuing to crosspublish for scala 2.10 as well?

**Comment by caniszczyk** [comment]
@pankajgupta I created #126 for that, seems fairly easy to do

**Pull request merged**
