### PR TITLE
Migration from Ostrich to Metrics: Fix typos

### PR DESCRIPTION
**Pull request by AnishShah**
I'm really sorry for the typos.

### CODE REVIEW

**Comment by pankajgupta** [comment]
np, and thanks for fixing quickly.

**Comment by pankajgupta** [comment]
ummm, @AnishShah it throws exception at runtime. Hope you are using java 1.6.
Try:
./sbt 'project cassovary-server' run

**Comment by AnishShah** [comment]
Sorry. Checking.. It works properly on 1.7 
Checking on 1.6
Sorry

**Comment by AnishShah** [comment]
@pankajgupta Finagle has [dropped support for Java 6.](https://groups.google.com/forum/#!searchin/finaglers/support$20java$206/finaglers/3IFfjryHbVo/r9osYwyfI60J)

What to do now?

**Comment by AnishShah** [comment]
@pankajgupta [BufferPoolMXBean](http://docs.oracle.com/javase/7/docs/api/java/lang/management/BufferPoolMXBean.html) was added in Java 7. So, it throws java.lang.NoClassDefFoundError: for Java 6.

**Comment by pankajgupta** [comment]
Really, Chris? I thought Java 1.7 has problems with Mac OS X (that's why I
have Java 6). In any case, Java 6 is still quite around, right?

**Comment by pankajgupta** [comment]
Aha -- my bad in that I was carrying an old java version. Verified that this works alright on java 8 (the latest version), so we are all good.

**Comment by AnishShah** [comment]
No changes needed then?

**Comment by pankajgupta** [comment]
correct, all is good and we can close the issue.

**Pull request merged**
